batch_size: 64
dataset_name: my_dataset.MyDataset
hidden_dim: 256
input_dim: 784
loss_name: ce
lr: 0.001
model_name: my_model.MyModel
num_classes: 10
num_workers: 4
train_data_path: ./data/mnist/train-images-idx3-ubyte/train-images-idx3-ubyte
train_label_path: ./data/mnist/train-labels-idx1-ubyte/train-labels-idx1-ubyte
val_data_path: ./data/mnist/t10k-images-idx3-ubyte/t10k-images-idx3-ubyte
val_label_path: ./data/mnist/t10k-labels-idx1-ubyte/t10k-labels-idx1-ubyte
